// 256-thread variant of mul_mat_vec_q4_1_dp4a.
// Larger workgroup -> more waves/group on wide GPUs (wave>=32),
// matching the Q4_0 mr256 pattern (fl=56) for small-K models
// where the 32t variant leaves SMs underutilized.
// Generated by including the parameterised source with GROUP_SIZE=256.
#define GROUP_SIZE 256
#include "mul_mat_vec_q4_1_dp4a.hlsl"
