// 32-thread variant of mul_mat_vec_q4k_dp4a.
// Smaller workgroup -> more workgroups in flight on small-wave GPUs (e.g. Intel Arc, wave=16).
// Generated by including the parameterised source with GROUP_SIZE=32.
#define GROUP_SIZE 32
#include "mul_mat_vec_q4k_dp4a.hlsl"
