// 256-thread variant of mul_mat_vec_q5_0_dp4a.
// Larger workgroup -> more waves/group on wide GPUs (wave>=32),
// matching the Q8_0 mr256 (fl=44), IQ4_NL mr256 (fl=45), and
// Q4_0 mr256 (fl=46) pattern for small-K, small-models where the
// 32-thread variant leaves SMs underutilized.
// Generated by including the parameterised source with GROUP_SIZE=256.
#define GROUP_SIZE 256
#include "mul_mat_vec_q5_0_dp4a.hlsl"
