#!/usr/bin/env python3
"""Convert the SLM reasoning prompt files into laya-cli scenario files.

The reasoning/*.txt files are written for a *generative* SLM: they carry a long
"Task:" block describing a JSON output contract, and their options are
third-person meta-descriptions ("The player mentions ...").

Laya is a scorer, not a generator, so the conversion:
  * keeps Global Context + Situation + the question + the player's reply
    as LAYA_STATE,
  * drops the Task: block entirely (it describes an output format Laya has no
    way to produce),
  * strips the repeated "The player ..." boilerplate from each option so the
    only text Laya sees is what actually distinguishes the options.

Usage: python convert_reasoning_to_laya.py <src_dir> <dst_dir>
"""

import os
import re
import sys

# boilerplate that every option repeats; it carries no discriminating signal
PREFIXES = [
    "The player mentions having ",
    "The player mentions that they ",
    "The player mentions they ",
    "The player mentions that ",
    "The player mentions ",
    "The player want to talk about ",
    "The player wants to talk about ",
    "The player talks about ",
    "The player answers ",
    "The player says ",
    "The player ",
]


def strip_prefix(text):
    for p in PREFIXES:
        if text.lower().startswith(p.lower()):
            rest = text[len(p):].strip()
            return (rest[0].upper() + rest[1:]) if rest else text
    return text


def convert(path):
    raw = open(path, encoding="utf-8", errors="replace").read()

    m = re.search(r"Global Context:\s*(.*?)\n\s*Situation:", raw, re.S)
    context = m.group(1).strip() if m else ""

    m = re.search(r"Situation:\s*(.*?)\n\s*Task:", raw, re.S)
    situation = m.group(1).strip() if m else ""

    m = re.search(r'ask them:\s*"(.*?)"\s*$', situation, re.S | re.M)
    question = m.group(1).strip() if m else ""
    # the question line is re-emitted explicitly below
    situation = re.sub(r"\n?Mara then turns to the player.*$", "", situation, flags=re.S).strip()

    m = re.search(r"Options:\s*\[(.*?)\]", raw, re.S)
    options = []
    if m:
        for key, text in re.findall(r'"\s*([a-z])\.\s*(.*?)"\s*,?\s*(?:\n|$)', m.group(1)):
            options.append((key, strip_prefix(text.strip())))

    body = raw.split("CUSTOM_PROMPT", 1)[1] if "CUSTOM_PROMPT" in raw else ""
    utterances = [l.strip() for l in body.replace("END_SECTION", "").strip().splitlines() if l.strip()]

    return context, situation, question, options, utterances


def emit(name, context, situation, question, options, utterances):
    out = []
    out.append("# Laya scenario converted from examples/llm-infer/prompts/reasoning/%s" % name)
    out.append("# Generated by convert_reasoning_to_laya.py -- edit the generated file,")
    out.append("# not this header, once you start tuning it.")
    out.append("#")
    out.append("# The source file targets a generative SLM. Two things were dropped because")
    out.append("# they are meaningless to a scorer: the 'Task:' block (a JSON output")
    out.append("# contract) and the repeated 'The player ...' prefix on every option.")
    out.append("#")
    out.append("# LAYA_PROMPTS carries no gold labels yet, so laya-cli reports the choice")
    out.append("# distribution and mean confidence instead of accuracy. Add '<key> | ' in")
    out.append("# front of an utterance to label it.")
    out.append("")
    out.append("LAYA_STATE")
    if context:
        out.append(context)
        out.append("")
    if situation:
        out.append(situation)
        out.append("")
    out.append('Mara asked the player: "%s"' % question)
    out.append('The player answered: "{message}"')
    out.append("END_SECTION")
    out.append("")
    out.append("LAYA_CHOICE")
    out.append("instructions: Mara asked the player: \"%s\". "
               "Which of these descriptions best matches what the player just answered?" % question)
    for key, text in options:
        out.append("%s: %s" % (key, text))
    out.append("END_SECTION")
    out.append("")
    out.append("LAYA_PROMPTS")
    out.extend(utterances)
    out.append("END_SECTION")
    return "\n".join(out) + "\n"


def main():
    src, dst = sys.argv[1], sys.argv[2]
    # The Global Context preamble is identical across every scenario and is
    # saturated with thematic words ("trauma", "memories", "therapy"). Laya
    # scores options against the whole state, so that preamble biases every
    # decision toward whichever option shares its vocabulary: on D1 it drove
    # 38 of 40 utterances onto option c ("her trauma") regardless of what the
    # player actually said. It is dropped by default; --keep-context restores
    # it for comparison.
    keep_context = "--keep-context" in sys.argv
    os.makedirs(dst, exist_ok=True)
    for name in sorted(os.listdir(src)):
        if not re.match(r"^D\d+(_\d+)?\.txt$", name):
            continue
        ctx, sit, q, opts, utts = convert(os.path.join(src, name))
        if not keep_context:
            ctx = ""
        text = emit(name, ctx, sit, q, opts, utts)
        out_path = os.path.join(dst, "laya_" + name)
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("%-12s -> %-22s %d options, %d utterances" % (name, "laya_" + name, len(opts), len(utts)))


if __name__ == "__main__":
    main()
